// Generated by `cargo test -p receiverproxy-daemon --features ts` from the Rust request and
// response structs (crates/daemon/src/api.rs, jobs.rs, crates/rcvbp-wasm/src/api.rs,
// crates/wall, crates/sources). Do not edit; rerun the test.

export type Card = {
  controller: number;
  card_id: number;
  /**
   * The model name `config/cards/` gives the id byte; null when none does.
   */
  model: string | null;
  ver_major: number;
  ver_minor: number;
  cols: number;
  rows: number;
};
export type Stream = "out" | "err";
export type Line = {
  stream: Stream;
  text: string;
};
export type Outcome = {
  lines: Array<Line>;
  files: Array<string>;
};
export type GatedOutcome = {
  committed: boolean;
  lines: Array<Line>;
  files: Array<string>;
};
export type JobKind = "provision" | "firmware/install" | "flash/snapshot" | "flash/restore" | "show/video" | "show/hold" | "show/stream";
export type JobState = "running" | "done" | "failed" | "cancelled";
export type JobResult = GatedOutcome | Outcome;
export type Job = {
  id: string;
  kind: JobKind;
  state: JobState;
  started: string;
  finished: string | null;
  lines: Array<Line>;
  error: string | null;
  result: JobResult | null;
};
export type Fit = "stretch" | "contain" | "cover";
export type Pattern = "rgb" | "border" | "rows" | "gradient" | "white";
export type Started = {
  id: string;
};
export type ShowKind = "blank" | "still" | "pattern" | "video" | "stream";
export type Show = {
  kind: ShowKind;
  /**
   * What it came from: the pattern name, the file, the colour, the
   * pushing client.
   */
  source: string;
  /**
   * Frames per second for a video or a pushed stream; null for a still.
   */
  fps: number | null;
  /**
   * The wall it is drawn on, as `WxH, N cards`.
   */
  layout: string;
  /**
   * RFC 3339, when it went up.
   */
  started: string;
  /**
   * The job that keeps it there, when one does.
   */
  job: string | null;
};
export type JobBrief = {
  id: string;
  kind: JobKind;
  state: JobState;
  started: string;
};
export type State = {
  /**
   * Null until the daemon has put anything on the panel.
   */
  show: Show | null;
  brightness: number;
  /**
   * The last discovery result, as `GET /health` reports it.
   */
  cards: Array<Card>;
  /**
   * The newest job started in this run; null before the first.
   */
  job: JobBrief | null;
};
export type Health = {
  version: string;
  iface?: string;
  cards?: Array<Card>;
};
export type DiscoverReq = {
  /**
   * Seconds to listen; 3 by default.
   */
  wait?: number;
};
export type Cards = {
  cards: Array<Card>;
};
export type Settings = {
  iface: string;
  brightness: number;
  /**
   * A model from `config/cards/` overriding what discovery reports;
   * `None` follows the last discovered card.
   */
  card: string | null;
};
export type Brightness = {
  value: number;
};
export type ShowImageReq = {
  path: string;
  /**
   * `stretch` by default, as `rxp show image`.
   */
  fit?: Fit;
  hold?: boolean;
};
export type ShowVideoReq = {
  path: string;
  loop?: boolean;
  /**
   * 30 by default.
   */
  fps?: number;
  /**
   * `contain` by default.
   */
  fit?: Fit;
  /**
   * The daemon's wall by default.
   */
  layout?: Canvas;
};
export type ShowPatternReq = {
  name: Pattern;
  hold?: boolean;
};
export type ShowFillReq = {
  /**
   * `RRGGBB`, `#` optional.
   */
  rgb: string;
  hold?: boolean;
};
export type FrameQuery = {
  /**
   * What to call the stream in `GET /state`; `frame push` by default.
   */
  source?: string;
  /**
   * `contain` by default, as `rxp show serve`.
   */
  fit?: Fit;
};
export type SpecReq = {
  spec_toml: string;
};
export type GenFileSet = {
  /**
   * Base64, `<name>.rcvbp`.
   */
  rcvbp: string;
  /**
   * Base64, 256 bytes.
   */
  basic_pack: string;
  /**
   * Base64, 65536 bytes; null when the image could not be built.
   */
  block7: string | null;
  /**
   * The `<name>-sources.txt` text.
   */
  sources_txt: string;
};
export type GenFiles = {
  name: string;
  files: GenFileSet;
  sources: Array<string>;
  notes: Array<string>;
};
export type ConfigReadReq = {
  index?: number;
  /**
   * `FLASH_PAGE_BASIC_PARAM` by default.
   */
  page?: number;
  /**
   * 64 by default.
   */
  max_chunks?: number;
  /**
   * Seconds; 2 by default.
   */
  wait?: number;
};
export type ConfigRead = {
  rcvbp: string;
  lines: Array<Line>;
};
export type ConfigWriteReq = {
  /**
   * Base64 of the `.rcvbp` file.
   */
  rcvbp: string;
  commit?: boolean;
  index?: number;
  wait?: number;
};
export type ConfigWriteQuery = {
  commit?: boolean;
  index?: number;
  wait?: number;
};
export type ConfigSendReq = {
  spec_toml: string;
  chip_only?: boolean;
  /**
   * 8 by default.
   */
  gap_ms?: number;
};
export type ProvisionReq = {
  spec_toml: string;
  /**
   * A `config/firmware.toml` name, a path, or `auto` for the image
   * `POST /firmware/pick` chooses.
   */
  firmware_path?: string;
  position: [number, number];
  /**
   * The card's position in the Ethernet chain; absent, the EEPROM frames
   * broadcast and a chain of more than one card is refused.
   */
  index?: number;
  /**
   * `<data dir>/snapshots/<unix seconds>` by default.
   */
  snapshot_dir?: string;
  commit?: boolean;
  wait?: number;
};
export type SnapshotReq = {
  dir?: string;
  index?: number;
  wait?: number;
};
export type RestoreReq = {
  dir: string;
  commit?: boolean;
  index?: number;
  wait?: number;
};
export type FirmwareReq = {
  path: string;
  commit?: boolean;
  golden?: boolean;
  /**
   * Seconds; 120 by default.
   */
  timeout?: number;
  /**
   * 3000 by default.
   */
  chunk_delay_us?: number;
  /**
   * Seconds; 4 by default.
   */
  wait?: number;
};
export type UploadQuery = {
  name?: string;
};
export type FirmwareUpload = {
  name: string;
  /**
   * The path on the daemon's machine; `POST /firmware/install` takes it.
   */
  path: string;
  size: number;
  /**
   * Lowercase hex of the uploaded bytes.
   */
  sha256: string;
  /**
   * True when the name is in `config/firmware.toml` and the bytes match
   * its entry; false when the manifest lists no such name.
   */
  verified: boolean;
  /**
   * The manifest's sha256 for that name, when it lists one.
   */
  manifest_sha256?: string;
};
export type FirmwareCandidate = {
  name: string;
  version: string;
  /**
   * The board revision in the name; absent when it carries none.
   */
  pcb?: string;
  kind: string;
  chips: Array<string>;
  size: number;
  sha256: string;
  score: number;
  reasons: Array<string>;
};
export type FirmwarePick = {
  /**
   * The spec's chip, as the ranking read it from the chip library.
   */
  chip: string;
  /**
   * The card model the ranking used.
   */
  card: string;
  /**
   * The image `provision --firmware auto` would install; null when the
   * ranking refused.
   */
  chosen?: string;
  /**
   * The refusal text; null when one was chosen.
   */
  refused?: string;
  candidates: Array<FirmwareCandidate>;
};
export type ScreenSizeQuery = {
  index?: number;
  wait?: number;
};
export type Size = {
  width: number;
  height: number;
};
export type ScreenSizeReq = {
  width: number;
  height: number;
  commit?: boolean;
  index?: number;
  wait?: number;
};
export type SizeOutcome = {
  width: number;
  height: number;
  committed: boolean;
  lines: Array<Line>;
  files: Array<string>;
};
export type ReloadReq = {
  index?: number;
  full?: boolean;
};
export type TestModeReq = {
  /**
   * 0-255; 0 is off.
   */
  n: number;
  index?: number;
};
export type SetLayoutReq = {
  panel_width: number;
  panel_height: number;
  index?: number;
};
export type Status = "verified" | "derived" | "stub";
export type Meta = {
  /**
   * Pixel pitch in millimetres, when the spec describes one physical module.
   */
  pitch_mm?: number;
  status: Status;
  /**
   * Vendor files the values were taken from.
   */
  sources: number;
  /**
   * Share (0..1) of the files for this module class that agree with the
   * values; absent when nothing was counted.
   */
  agreement?: number;
  /**
   * A few of the source files by name.
   */
  examples: Array<string>;
  /**
   * Control-system vendors whose config files the sources are (the
   * format the values were taken from), not who makes the panel.
   */
  vendors: Array<string>;
  notes?: string;
  /**
   * Who makes the panel.
   */
  maker?: string;
  /**
   * The maker's model name.
   */
  product?: string;
  /**
   * Product page.
   */
  url?: string;
  /**
   * Specification sheet.
   */
  datasheet?: string;
  /**
   * Photo.
   */
  image?: string;
  image_source?: string;
};
export type EntryModule = {
  width: number;
  height: number;
  scan: number;
};
export type EntryChip = {
  /**
   * The `[chip].library` path.
   */
  library: string;
  /**
   * The library's `name`.
   */
  name: string;
  family_id: number;
};
export type Entry = {
  path: string;
  name: string;
  meta: Meta;
  module: EntryModule;
  chip: EntryChip;
  /**
   * Registry formats that can generate for the entry.
   */
  formats: Array<string>;
};
export type Format = {
  /**
   * The name `--format` and the site use.
   */
  name: string;
  vendor: string;
  /**
   * File extension without the dot.
   */
  extension: string;
  /**
   * The codec writes a file from a spec.
   */
  generate: boolean;
  /**
   * The codec reads a file back into a spec.
   */
  import: boolean;
};
export type GenFile = {
  name: string;
  bytes: Uint8Array;
};
export type Generated = {
  name: string;
  files: Array<GenFile>;
  sources: Array<string>;
  notes: Array<string>;
};
export type Imported = {
  /**
   * The spec as TOML, the form the Builder edits.
   */
  spec_toml: string;
  /**
   * Fields the file did not determine, by name.
   */
  unresolved: Array<string>;
  /**
   * The registry format the file was read as, or `spec` for a TOML spec.
   */
  format: string;
};
export type Record01 = {
  module_width: number;
  module_height_stored: number;
  scan: number;
  serial_clock: number;
  gray: number;
  luminance_level: number;
  max_width: number;
  max_height: number;
  grid: [number, number];
  line_dir: number;
  split_segment: number;
  segments: number;
  min_oe: number;
  hr_style: number;
  hr_scan_style: number;
  chip_id: number;
  swap_ramp: Uint8Array;
  chip_custom: Uint8Array;
};
export type RecordInfo = {
  offset: number;
  type: string;
  id: number;
  length: number;
  nonzero: number;
  empty: boolean;
  description: string;
  fields: Record01 | null;
};
export type Inspection = {
  version: number;
  cabinet: [number, number] | null;
  records: Array<RecordInfo>;
};
export type RecordDiff = {
  type: string;
  len_a: number;
  len_b: number;
  offsets: Array<number>;
};
export type Diff = {
  a_records: number;
  b_records: number;
  only_a: Array<string>;
  only_b: Array<string>;
  records: Array<RecordDiff>;
};
export type LibraryChip = {
  path: string;
  name: string;
  toml: string;
  /**
   * The library's own `status`; `derived` when the file states none.
   */
  status: Status;
};
export type LibraryPanel = {
  path: string;
  name: string;
  toml: string;
  /**
   * The spec's `[meta] status`; `derived` when the file states none.
   */
  status: Status;
};
export type Libraries = {
  chips: Array<LibraryChip>;
  panels: Array<LibraryPanel>;
};
export type Rotation = "none" | "cw90" | "ccw90" | "rot180";
export type Receiver = {
  index: number;
  /**
   * The card's top-left on the screen: the same numbers given to
   * `rxp provision --position x,y`, which is what the card's EEPROM
   * control area keeps of the stream.
   */
  x: number;
  y: number;
  width: number;
  height: number;
};
export type Panel = {
  /**
   * Which receiving card drives this panel.
   */
  receiver: number;
  /**
   * Where the panel's top-left sits in the receiver's own pixel space.
   */
  receiver_x: number;
  receiver_y: number;
  /**
   * Where the panel's top-left sits on the logical canvas.
   */
  x: number;
  y: number;
  /**
   * Panel size as it appears on the canvas, after rotation.
   */
  width: number;
  height: number;
  rotation: Rotation;
  flip_x: boolean;
  flip_y: boolean;
};
export type Canvas = {
  width: number;
  height: number;
  receivers: Array<Receiver>;
  panels: Array<Panel>;
};
