[package]
name = "e120-rcvbp"
description = "Parser for Colorlight .rcvbp receiver-parameter files"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
flate2.workspace = true
serde.workspace = true

[lints]
workspace = true

[dev-dependencies]
toml.workspace = true
