[package]
name = "e120-cli"
description = "Command-line tool to configure and drive Colorlight receiver cards"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "e120"
path = "src/main.rs"

[dependencies]
e120-commands.workspace = true
e120-server.workspace = true
e120-canvas.workspace = true

anyhow.workspace = true
libc.workspace = true
clap.workspace = true
serde_json.workspace = true

[lints]
workspace = true
