[package]
name = "e120-cli"
description = "Command-line tool to configure and drive Colorlight receiver cards"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "e120"
path = "src/main.rs"

[dependencies]
e120-proto.workspace = true
e120-rcvbp.workspace = true
e120-net.workspace = true

anyhow.workspace = true
clap.workspace = true
image.workspace = true
