//! `cargo test -p daemon --features ts` writes `web/src/api/types.ts` from
//! the request and response structs, and fails when the committed file was
//! not what it wrote: rerun it and commit the result.

#![cfg(feature = "ts")]

use daemon::api::*;
use daemon::jobs::{GatedOutcome, Job, JobKind, JobResult, JobState, Line, Outcome, Stream};
use panelspec::{Meta, Origin, Status};
use rcvbp::Format;
use rcvbp_wasm::api::{
    Diff, Entry, EntryChip, EntryModule, GenFile, Generated, Imported, Inspection, Libraries,
    LibraryChip, LibraryPanel, Record01, RecordDiff, RecordInfo,
};
use sources::{Fit, Pattern};
use std::path::Path;
use ts_rs::{Config, TS};
use wall::{Canvas, Panel, Receiver, Rotation};

/// One exported type: its name, its declaration, and the names it refers to.
struct Decl {
    name: String,
    text: String,
    deps: Vec<String>,
}

fn decl<T: TS + 'static>(cfg: &Config) -> Decl {
    Decl {
        name: T::ident(cfg),
        text: T::decl(cfg),
        deps: T::dependencies(cfg).into_iter().map(|d| d.ts_name).collect(),
    }
}

macro_rules! decls {
    ($cfg:expr; $($t:ty),* $(,)?) => { vec![$(decl::<$t>($cfg)),*] };
}

/// The file's text: every type in section order, one `export type` each.
fn render() -> String {
    // JavaScript numbers hold every value the API carries.
    let cfg = Config::new().with_large_int("number");
    let decls = decls![&cfg;
        // docs/ui.md section 2: common shapes
        Card, Stream, Line, Outcome, GatedOutcome, JobKind, JobState, JobResult, Job,
        Fit, Pattern, Started,
        // routes, in the order of the section
        Health, DiscoverReq, Cards, Settings, Brightness, ShowImageReq, ShowVideoReq,
        ShowPatternReq, ShowFillReq, SpecReq, GenFileSet, GenFiles, ConfigReadReq, ConfigRead,
        ConfigWriteReq, ConfigSendReq, ProvisionReq, SnapshotReq, RestoreReq, FirmwareReq,
        ScreenSizeQuery, Size, ScreenSizeReq, SizeOutcome, ReloadReq, TestModeReq, SetLayoutReq,
        // section 3: the WASM surface
        Status, Origin, Meta, EntryModule, EntryChip, Entry, Format, GenFile, Generated, Imported, Record01,
        RecordInfo, Inspection, RecordDiff, Diff, LibraryChip, LibraryPanel, Libraries,
        // section 4: the layout JSON
        Rotation, Receiver, Panel, Canvas,
    ];
    let names: Vec<&str> = decls.iter().map(|d| d.name.as_str()).collect();
    for d in &decls {
        for dep in &d.deps {
            assert!(
                names.contains(&dep.as_str()),
                "{} refers to {dep}, which is not in the exported list",
                d.name
            );
        }
    }
    let mut out = String::from(
        "// Generated by `cargo test -p daemon --features ts` from the Rust request and\n\
         // response structs (crates/daemon/src/api.rs, jobs.rs, crates/rcvbp-wasm/src/api.rs,\n\
         // crates/wall, crates/sources). Do not edit; rerun the test.\n\n",
    );
    for d in &decls {
        out.push_str("export ");
        out.push_str(&pretty(&d.text));
        out.push('\n');
    }
    out
}

/// ts-rs writes an object type on one line, doc comments included; this
/// puts one field per line. Aliases and unions stay as they are.
fn pretty(decl: &str) -> String {
    let Some(open) = decl.find("= {") else {
        return decl.to_owned();
    };
    let Some(body) = decl[open + 3..].strip_suffix("};") else {
        return decl.to_owned();
    };
    let mut out = format!("{}= {{\n", &decl[..open]);
    for field in split_fields(body) {
        for line in field.lines() {
            out.push_str("  ");
            out.push_str(line);
            out.push('\n');
        }
        // The field itself is the last line; the ones before are its comment.
        out.insert(out.len() - 1, ';');
    }
    out.push_str("};");
    out
}

/// The fields of `a: T, b: U, `, split at the commas outside brackets and
/// doc comments.
fn split_fields(body: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut depth = 0i32;
    let mut in_comment = false;
    let mut current = String::new();
    let mut chars = body.chars().peekable();
    while let Some(c) = chars.next() {
        if in_comment {
            if c == '*' && chars.peek() == Some(&'/') {
                in_comment = false;
            }
        } else {
            match c {
                '/' if chars.peek() == Some(&'*') => in_comment = true,
                '[' | '<' | '{' | '(' => depth += 1,
                ']' | '>' | '}' | ')' => depth -= 1,
                ',' if depth == 0 => {
                    let f = current.trim();
                    if !f.is_empty() {
                        fields.push(f.to_owned());
                    }
                    current.clear();
                    continue;
                }
                _ => {}
            }
        }
        current.push(c);
    }
    let f = current.trim();
    if !f.is_empty() {
        fields.push(f.to_owned());
    }
    fields
}

#[test]
fn types_ts_is_what_the_structs_say() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/src/api/types.ts");
    let want = render();
    let have = std::fs::read_to_string(&path).unwrap_or_default();
    if have != want {
        std::fs::write(&path, &want).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
        panic!(
            "{} was stale and has been rewritten; commit it",
            path.display()
        );
    }
}
