#!/usr/bin/env python3
"""Derive chip libraries and panel specs from the vendor .rcvbp corpus.

Usage:
  corpus-mine.py [--corpus DIR]... [--min-files 20] [--min-panel-files 6] [--min-agree 0.5] [--out config]
  A chip library is the per-byte mode over the files declaring that chip; a panel
  spec is written only where the generator's mapping formula fits the files' pixel
  maps exactly. Everything written here carries `status = "derived"`: the values
  come from vendor configuration files, not from a bench.
"""
import argparse
import collections
import glob
import json
import os
import re

from mapdump import records

CORPUS = ['vendor/led-config-files/rcvbp']


def load(path):
    """The fields the generator needs, from one file; None if unreadable."""
    try:
        recs = {t & 0xff: b for t, b in records(path)}
    except Exception:
        return None
    r = recs.get(0x01)
    if r is None or len(r) < 0x100:
        return None
    hi = lambda o: r[o] if len(r) > o else 0
    regs = None
    if 0x84 in recs:
        body = recs[0x84]
        regs = {}
        for i in range(0, len(body) - 3, 4):
            a = body[i]
            if a == 0 and not any(body[i + 1:i + 4]):
                break
            regs[a] = tuple(body[i + 1:i + 4])
    return {
        'name': os.path.basename(path),
        'w': r[0], 'h': r[1] * 2, 'scan': r[0x20],
        'sck': r[0x21] | (r[0x22] << 8), 'gray': r[0x23],
        'chip': r[0x36] | (hi(0x204) << 8), 'sub': r[0xE9] | (hi(0x205) << 8),
        'control': tuple(r[0xC4:0xD8]), 'custom': tuple(r[0x6A:0x7A]), 'custom_ex': tuple(r[0xE0:0xE4]),
        'line_dir': r[0x3C], 'data_groups': r[0x44], 'f02f': r[0x2F], 'f043': r[0x43],
        'gains': tuple(r[0x32:0x36]),
        'regs': regs, 'map': recs.get(0x03),
    }


def mode(values):
    c = collections.Counter(values)
    v, n = c.most_common(1)[0]
    return v, n / len(values)


def bytes_mode(tuples, ignore=()):
    """Per-byte mode across equal-length tuples; returns (tuple, min agreement
    over the bytes not in `ignore`, per-byte agreement list)."""
    out, per = [], []
    for i in range(len(tuples[0])):
        v, a = mode([t[i] for t in tuples])
        out.append(v)
        per.append(a)
    agree = min((a for i, a in enumerate(per) if i not in ignore), default=1.0)
    return tuple(out), agree, per


# Chip-control bytes that vary with scan/refresh inside one chip family across
# the corpus (10-13 are the GCLK counts); they do not count against agreement.
CONTROL_VARIES = (7, 8, 10, 11, 12, 13, 16)


def toml_bytes(bs):
    return '[' + ', '.join(f'0x{b:02x}' for b in bs) + ']'


def chip_library(chip, files, names, out_dir, min_agree):
    name = names.get(f'0x{chip:04x}', f'chip-0x{chip:04x}')
    control, a_ctl, per = bytes_mode([f['control'] for f in files], CONTROL_VARIES)
    sck, _ = mode([f['sck'] for f in files])
    gray, _ = mode([f['gray'] for f in files])
    sub, _ = mode([f['sub'] for f in files])
    f02f, _ = mode([f['f02f'] for f in files])
    f043, _ = mode([f['f043'] for f in files])
    with_regs = [f for f in files if f['regs']]
    addressed = len(with_regs) >= len(files) / 2
    if a_ctl < min_agree:
        return None, f'{name} 0x{chip:04x}: control block agreement {a_ctl:.2f} < {min_agree}, skipped ({len(files)} files)'
    ex = ', '.join(f['name'] for f in files[:3])
    slug = re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')
    lines = [
        f'# {name} (chip id 0x{chip:04X}), derived from {len(files)} vendor configuration files.',
        f'# Values are the per-byte mode across those files. Chip-control bytes 7-8,',
        f'# 10-13 (GCLK counts) and 16 vary with scan/refresh inside a family: compare',
        f'# against a vendor file for the exact panel before trusting them. The other',
        f'# bytes agree in {a_ctl * 100:.0f}% of the files. Never driven on a bench.',
        f'# Per-byte agreement: {" ".join(f"{int(a * 100)}" for a in per)}',
        f'# Examples: {ex}',
        f'# Generated by scripts/corpus-mine.py; regenerate rather than edit.',
        '',
        f'name = "{name}"',
        'status = "derived"',
        f'family_id = 0x{chip:04X}',
        f'sub_id = 0x{sub:04X}',
        f'serial_clock = {sck}',
        f'chip_control = {toml_bytes(control)}',
    ]
    if addressed:
        # Register order as the vendor writes it: the first file's order, then
        # any address only other files carry.
        order = list(with_regs[0]['regs'])
        for f in with_regs[1:]:
            order += [a for a in f['regs'] if a not in order]
        regs = {}
        agree_min = 1.0
        for a in list(order):
            vals = [f['regs'][a] for f in with_regs if a in f['regs']]
            # 0x07 is required by the generator (GCLK count check).
            if a != 0x07 and len(vals) < len(with_regs) / 5:
                order.remove(a)
                continue
            v, ag = mode(vals)
            regs[a] = v
            agree_min = min(agree_min, ag)
        if 0x07 not in regs:
            # Not the (register, R, G, B) quad layout the generator emits.
            return None, f'{name} 0x{chip:04x}: record 0x84 layout not understood (no register 0x07), skipped ({len(files)} files)'
        lines += ['order = [' + ', '.join(f'0x{a:02x}' for a in order) + ']',
                  f'# register table from {len(with_regs)} files (lowest per-register agreement {agree_min * 100:.0f}%);',
                  '# register 0x02 is replaced by scan-1 on load.',
                  '[registers]']
        for a in order:
            lines.append(f'0x{a:02x} = {toml_bytes(regs[a])}')
    else:
        custom, a_cus, _ = bytes_mode([tuple(b & (0xF0 if i in (2, 4, 6) else 0xFF) for i, b in enumerate(f['custom']))
                                    for f in files])
        custom_ex, _, _ = bytes_mode([f['custom_ex'] for f in files])
        base = custom[2] & 0xF0
        lines += [f'# Non-addressed chip: no record 0x84 in {len(files) - len(with_regs)} of {len(files)} files;',
                  f'# the configuration is the SChipCustom block (agreement {a_cus * 100:.0f}%, scan nibble masked).',
                  f'chip_custom = {toml_bytes(custom)}',
                  f'chip_custom_scan_patch = {{ bytes = [2, 4, 6], mask = 0x0F, base = 0x{base:02X} }}',
                  f'chip_custom_ex = {toml_bytes(custom_ex)}',
                  'emit_record_84 = false',
                  f'gray_bits = {gray}']
    lines += ['', '[record01_overrides]', f'"0x02F" = 0x{f02f:02X}', f'"0x043" = 0x{f043:02X}', '']
    path = os.path.join(out_dir, 'chips', f'{slug}.toml')
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w').write('\n'.join(lines))
    return path, f'{name} 0x{chip:04x}: {len(files)} files, control {a_ctl * 100:.0f}%, {"registers" if addressed else "custom block"} -> {path}'


def generated_map(w, h2, scan, block, rg, rl):
    """The generator's record-0x03 formula (crates/rcvbp/src/spec/mapping.rs)."""
    groups = h2 // scan
    out = bytearray((w * h2).to_bytes(2, 'little'))
    blk = max(1, min(block, w))
    for i in range(w * h2):
        row, col = divmod(i, w)
        line = (scan - 1 - row % scan) if rl else row % scan
        group = (groups - 1 - row // scan) if rg else row // scan
        slot = (col // blk) * (groups * blk) + group * blk + col % blk
        out.append(line)
        out += slot.to_bytes(2, 'little')
    return bytes(out)


def fit_map(f):
    w, h2, scan = f['w'], f['h'] // 2, f['scan']
    if not (w and scan and h2 % scan == 0) or f['map'] is None:
        return None
    for block in sorted({w, w // 2, w // 4, w // 8} - {0}, reverse=True):
        for rg in (True, False):
            for rl in (False, True):
                if generated_map(w, h2, scan, block, rg, rl) == bytes(f['map']):
                    return block, rg, rl
    return None


def spec_head(slug, sources, agreement, examples, note):
    """The one comment line, `name` and the `[meta]` table of a derived spec
    (panelspec::Meta): the files that fit the wiring, the share of the class
    they are, three of them by name. Every corpus file is a Colorlight one."""
    notes = (f'Values are the majority across {sources} vendor configuration file'
             f'{"" if sources == 1 else "s"}, {agreement * 100:.0f}% of the files for this '
             'module class. Never driven on a bench.')
    if note:
        notes += ' ' + note
    return [
        '# generated by scripts/corpus-mine.py; regenerate rather than edit',
        '', f'name = "{slug}"', '',
        '[meta]', 'status = "derived"', f'sources = {sources}',
        f'agreement = {agreement:.2f}', f'examples = {json.dumps(examples)}', 'vendors = ["Colorlight"]',
        f'notes = {json.dumps(notes)}', '',
    ]


def panel_spec(key, files, chip_path, names, out_dir):
    w, h, scan, chip = key
    cname = names.get(f'0x{chip:04x}', f'chip-0x{chip:04x}')
    if chip_path is None:
        return None, f'{w}x{h} 1/{scan} {cname}: no chip library derived for it, skipped ({len(files)} files)'
    fits = [fit_map(f) for f in files]
    best, share = mode(fits)
    if best is None or share < 0.6:
        return None, f'{w}x{h} 1/{scan} {names.get(f"0x{chip:04x}", hex(chip))}: no majority wiring fit across {len(files)} files ({sum(1 for x in fits if x)} fit individually), skipped'
    files = [f for f, x in zip(files, fits) if x == best]
    block, rg, rl = best
    sck, _ = mode([f['sck'] for f in files])
    line_dir, _ = mode([f['line_dir'] for f in files])
    dg, _ = mode([f['data_groups'] for f in files])
    gains, _ = mode([f['gains'] for f in files])
    slug = f'{w}x{h}-{scan}s-' + re.sub(r'[^a-z0-9]+', '-', cname.lower()).strip('-')
    lib = os.path.relpath(chip_path)
    big = w * h // 2 > 4096
    note = (f'The pixel map has {w * h // 2} entries; the block-7 image builder packs at most 4096, '
            'so `rxp config gen` writes the .rcvbp but not the boot image.') if big else None
    lines = spec_head(slug, len(files), share, [f['name'] for f in files[:3]], note) + [
        '[module]', f'width = {w}', f'height = {h}', f'scan = {scan}', f'line_dir = {line_dir}',
        f'data_groups = {dg}', f'serial_clock = {sck}', '',
        '[screen]', f'width = {w}', f'height = {h}', '',
        '[chip]', f'library = "{lib}"', '',
        '[current]', f'gains = {list(gains)}', 'percent = [0.1, 0.1, 0.1]', '',
        '[mapping]', f'reversed_groups = {str(rg).lower()}', f'reversed_lines = {str(rl).lower()}', f'block = {block}', '',
        '[boot]', 'arm_at_boot = true', '',
    ]
    path = os.path.join(out_dir, 'panels', f'{slug}.toml')
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w').write('\n'.join(lines))
    return path, f'{w}x{h} 1/{scan} {cname}: {len(files)} files, block={block} rg={rg} rl={rl} -> {path}'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--min-files', type=int, default=20, help='chip families with fewer vendor files are left out')
    ap.add_argument('--min-panel-files', type=int, default=6, help='module classes with fewer vendor files are left out')
    ap.add_argument('--min-agree', type=float, default=0.5, help='lowest per-byte control-block agreement for a chip library')
    ap.add_argument('--corpus', action='append', help='directory of .rcvbp files, searched recursively (repeatable)')
    ap.add_argument('--out', default='config')
    a = ap.parse_args()
    names = json.load(open('config/chips/chip-names.json'))
    files = []
    for root in a.corpus or CORPUS:
        for p in glob.glob(os.path.join(root, '**', '*.rcvbp'), recursive=True):
            f = load(p)
            if f:
                files.append(f)
    print(f'{len(files)} configs parsed')

    by_chip = collections.defaultdict(list)
    for f in files:
        by_chip[f['chip']].append(f)
    chip_paths, log = {}, []
    for chip, fs in sorted(by_chip.items(), key=lambda kv: -len(kv[1])):
        if chip == 0 or len(fs) < a.min_files:
            continue
        path, msg = chip_library(chip, fs, names, a.out, a.min_agree)
        log.append(msg)
        if path:
            chip_paths[chip] = path
    print('\n'.join(log))

    by_geo = collections.defaultdict(list)
    for f in files:
        if f['map'] is not None and f['chip']:
            by_geo[(f['w'], f['h'], f['scan'], f['chip'])].append(f)
    print()
    for key, fs in sorted(by_geo.items(), key=lambda kv: -len(kv[1])):
        if len(fs) < a.min_panel_files:
            continue
        _, msg = panel_spec(key, fs, chip_paths.get(key[3]), names, a.out)
        print(msg)


main()
